version: "3.7"
services: 
  tomcat:
    container_name: nginx-tomcat
    build:
       context: ./tomcat
       args:
          NGINX_VERSION: 1.18.0
          START_NGINX: 1
       dockerfile: Dockerfile
    image: "nginx-tomcat:latest"
    ports: 
      - "9080:8080"
      - "80:80"
      - "7007:7007"
      - "9000:8000"
    environment: 
      - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Xmx8g -Xms8g -XX:MaxPermSize=1024m
      - CATALINA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
      - TZ=Europe/Rome
    volumes: 
      - ..\logs\tomcat:/usr/local/tomcat/logs/
      - ..\logs\nginx:/var/log/nginx/
      - ..\logs\nginx\etc:/etc/nginx/logs/
      - ..\webapps:/usr/local/tomcat/webapps/
      ## add nginx custom config files
      - ..\nginx-conf\*:/etc/nginx/
