version: '3.7'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=<ADMIN>
      - POSTGRES_PASSWORD=<ADMIN_PASSWORD>
      - TZ=Europe/Rome
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - '5432:5432'
    restart: unless-stopped

