version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<ADMIN>
      - MONGO_INITDB_ROOT_PASSWORD=<ADMIN_PASSWORD>
      - MONGO_INITDB_DATABASE=<USER-DB>
      - TZ=Europe/Rome
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'

